import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ApplicationContextProvider } from './context/AuthContext'
import { UserHeaderWrapper } from './components/UserHeaderWrapper/UserHeaderWrapper'

// import { config } from '@fortawesome/fontawesome';
import '@fortawesome/fontawesome-svg-core/styles.css';
// import { faTrash } from '@fortawesome/free-solid-svg-icons';

// config({
//   autoAddCss: true,
//   useFontAwesomeIcons: false,
// });


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApplicationContextProvider>
          <UserHeaderWrapper />

          {children}
        </ApplicationContextProvider>
      </body>
    </html>
  )
}
